In [2]:
import numpy as np
a=np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [6]:
b=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(b)
print("dimension:",np.shape(b))

[[1 2 3]
 [2 3 4]
 [3 4 5]]
dimension: (3, 3)


In [7]:
print(np.zeros((3,2)))

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [12]:
c=np.arange(10).reshape(5,2)
print(c)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
d=np.random.random([3,3])
print(d)

[[  8.61439694e-05   2.92230939e-01   4.56807506e-01]
 [  4.46278128e-01   8.35998718e-01   9.96226235e-01]
 [  9.54073603e-02   4.67757851e-01   9.53882240e-01]]


In [16]:
e=np.linspace(1,4,7)
print(e)

[ 1.   1.5  2.   2.5  3.   3.5  4. ]


In [17]:
f=np.arange(2,6,0.1)
print(f)

[ 2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4
  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9
  5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9]


In [19]:
g=np.floor((10*np.random.random((2,7))))
print(g)

[[ 3.  9.  3.  5.  8.  0.  5.]
 [ 0.  5.  2.  0.  7.  5.  2.]]


In [23]:
#multiplication

import numpy as np
a=np.arange(6).reshape((2,3))
b=np.arange(6).reshape((3,2))
c=np.dot(a,b)
print(c)

[[10 13]
 [28 40]]


In [24]:
print(np.transpose(c))

[[10 28]
 [13 40]]


In [26]:
#single value decomposition


import numpy as np
from scipy.linalg import svd
x=np.array([[1,2,3],[4,5,6],[5,6,7]])
u,s,t=svd(x)
print("x = ",x)
print("u = ",u)
print("s = ",s)
print("t = ",t)

x =  [[1 2 3]
 [4 5 6]
 [5 6 7]]
u =  [[-0.25775879  0.94609665  0.19611614]
 [-0.62014124 -0.00634259 -0.78446454]
 [-0.74093539 -0.32382234  0.58834841]]
s =  [  1.41499421e+01   8.82688844e-01   2.95742808e-16]
t =  [[-0.4553376  -0.5697434  -0.6841492 ]
 [-0.79120225 -0.09341194  0.60437836]
 [ 0.40824829 -0.81649658  0.40824829]]
