In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score
dataset = pd.read_csv('Book1.csv')
X = dataset.iloc[:, [1, 2]].values
y = dataset.iloc[:, -1].values
print(X)
print(y)
le = LabelEncoder()
k=le.fit_transform(X[:,0])
print(k)
f=le.fit_transform(X[:,1])
print(f)
label=le.fit_transform(y)
print(label)
q=(np.vstack((k, f)).T)
print(q)
X_train, X_test, y_train, y_test = train_test_split(q, label, test_size = 0.20, random_state =42)
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred  = classifier.predict(X_test)
print(y_pred)
print(y_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
ac = accuracy_score(y_test,y_pred)
print(ac)


[['sunny' 'hot']
 ['sunny' 'hot']
 ['overcast' 'hot']
 ['rainy' 'mild']
 ['rainy' 'cool']
 ['rainy' 'cool']
 ['overcast' 'cool']
 ['sunny' 'mild']
 ['sunny' 'cool']
 ['rainy' 'mild']
 ['sunny' 'mild']
 ['overcast' 'mild']
 ['overcast' 'hot']
 ['rainy' 'mild']]
['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']
[2 2 0 1 1 1 0 2 2 1 2 0 0 1]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]
[[2 1]
 [2 1]
 [0 1]
 [1 2]
 [1 0]
 [1 0]
 [0 0]
 [2 2]
 [2 0]
 [1 2]
 [2 2]
 [0 2]
 [0 1]
 [1 2]]
[0 1 0]
[1 1 0]
[[1 0]
 [1 1]]
0.666666666667


In [3]:
 luthfan kmct: from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import mean_squared_error,r2_score

irisData = load_iris()

x = irisData.data
y = irisData.target

x_train , x_test ,y_train ,y_test = train_test_split(x,y,test_size=7,random_state=42)

model = linear_model.LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
y_pred_train = model.predict(x_train)
print("mean square error",mean_squared_error(y_test,y_pred))
print("r2score",r2_score(y_test,y_pred))

SyntaxError: invalid syntax (<ipython-input-3-9f1e510a7232>, line 1)